export const API = "http://158.160.9.246";
export const ACTIONS = {
  GET_MY_PROFILE: "GET_MY_PROFILE",
  GET_POSTS: "GET_POSTS",
  GET_ONE_POST: "GET_ONE_POST",
  GET_PROFILES: "GET_PROFILES",
  GET_ONE_USERS: "GET_ONE_USERS",
};
